"""Constant definitions for the AtmoML model."""

# Geospatial constants should be 200
MAP_HEIGHT = 24
MAP_WIDTH = 24

# Other well-defined constants
INPUT_TIME_STEPS = 6
# OUTPUT_CHANNELS should be 5
OUTPUT_CHANNELS = 1
OUTPUT_TIME_STEPS = 8
NUM_SAPTIAL_FEATURES = 22
NUM_SPATIOTEMPORAL_FEATURES = 12
TIME_STEPS_PER_DAY = 4
LU_INDEX_VOCAB_SIZE = 61
EMBEDDING_DIM = 8
