# -*- coding: utf-8 -*-
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "pfdf==3.0.4",
#   "numpy>=2",
#   "pandas",
#   "scipy",
# ]
#
# [[tool.uv.index]]
# url = "https://code.usgs.gov/api/v4/groups/859/-/packages/pypi/simple"
# ///
"""Rainfall_scenario_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q148zAZkV4GhIWophRRVH221MY1kHf2H
"""



"""
This script generates design storm rainfall scenarios based on NOAA Atlas 14
precipitation-frequency data. The workflow includes:

1. Downloading NOAA Atlas 14 rainfall depth tables for a specified location.
2. Fitting Intensity-Duration-Frequency (IDF) curves.
3. Generating Chicago design storm hyetographs.
4. Exporting rainfall files for hydrodynamic models.

Author/Created by: Ashish Shrestha
Date: 2026-03-09

Notes
-----
Need to change lat/lon and output directory before running.
"""

"""
This script generates design storm rainfall scenarios based on NOAA Atlas 14
precipitation-frequency data. The workflow includes:

1. Downloading NOAA Atlas 14 rainfall depth tables for a specified location.
2. Fitting Intensity-Duration-Frequency (IDF) curves.
3. Generating Chicago design storm hyetographs.
4. Exporting rainfall files for hydrodynamic models.

Installation: pip install pfdf -i https://code.usgs.gov/api/v4/groups/859/-/packages/pypi/simple

Author/Created by: Ashish Shrestha
Date: 2026-03-16

Notes
-----
Need to change lat/lon and output directory before running.
"""

import argparse
from pathlib import Path
import numpy as np
import pandas as pd
from pfdf.data.noaa import atlas14
from scipy.optimize import curve_fit


SCENARIOS = [
    {"file_no": 1,  "return_period": "1",    "storm_duration_hours": 1.00, "add_tail_min": 0},
    {"file_no": 2,  "return_period": "5",    "storm_duration_hours": 1.00, "add_tail_min": 0},
    {"file_no": 3,  "return_period": "10",   "storm_duration_hours": 1.00, "add_tail_min": 0},
    {"file_no": 4,  "return_period": "25",   "storm_duration_hours": 2.00, "add_tail_min": 0},
    {"file_no": 5,  "return_period": "50",   "storm_duration_hours": 2.00, "add_tail_min": 0},
    {"file_no": 6,  "return_period": "100",  "storm_duration_hours": 3.00, "add_tail_min": 0},
    {"file_no": 7,  "return_period": "200",  "storm_duration_hours": 3.00, "add_tail_min": 0},
    {"file_no": 8,  "return_period": "500",  "storm_duration_hours": 3.00, "add_tail_min": 0},
    {"file_no": 9,  "return_period": "1000", "storm_duration_hours": 3.00, "add_tail_min": 0},
]


def part1_download_atlas14(lat, lon, out_dir):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    return Path(
        atlas14.download(
            lat=lat,
            lon=lon,
            statistic="mean",
            data="depth",
            series="pds",
            units="english",
            parent=out_dir,
            overwrite=True,
            timeout=60,  # NOAA PFDS can be slow; pfdf default of 10 s times out
        )
    )


def part2_generate_rainfall_files(
    atlas14_csv,
    output_dir,
    scenarios=SCENARIOS,
    dt_minutes=5,
    r_peak=0.35,
    max_fit_minutes=24 * 60,
):
    atlas14_csv = Path(atlas14_csv)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    def duration_to_minutes(text):
        s = str(text).strip().replace(":", "")
        if "min" in s:
            return float(s.split("-")[0])
        if "hr" in s:
            return float(s.split("-")[0]) * 60.0
        if "day" in s:
            return float(s.split("-")[0]) * 1440.0
        return np.nan

    def idf_func(t, a, b, c):
        return a / ((t + b) ** c)

    def chicago_intensity(t, D, a, b, c, r):
        Tp = r * D
        if t < Tp:
            tb = Tp - t
            x = tb / r + b
            return a * (((1 - c) * (tb / r) + b) / (x ** (1 + c)))
        if t > Tp:
            ta = t - Tp
            x = ta / (1 - r) + b
            return a * (((1 - c) * (ta / (1 - r)) + b) / (x ** (1 + c)))
        return a / (b ** c)

    def idf_iavg(dt_min, a, b, c):
        return a / ((dt_min + b) ** c)

    def chicago_hyetograph(duration_hours, dt_minutes, a, b, c, r):
        D = duration_hours * 60.0
        dt = float(dt_minutes)
        dt_hr = dt / 60.0
        N = int(round(D / dt))
        Tp = r * D
        t_edges = np.linspace(0, D, N + 1)
        depth = np.zeros(N, dtype=float)

        for k in range(N):
            t0, t1 = t_edges[k], t_edges[k + 1]
            tm = 0.5 * (t0 + t1)
            i = idf_iavg(dt, a, b, c) if (t0 <= Tp <= t1) else chicago_intensity(tm, D, a, b, c, r)
            depth[k] = i * dt_hr

        return pd.DataFrame(
            {
                "time_sec": (np.arange(N) * dt * 60).astype(int),
                "depth_in": depth,
            }
        )

    def append_zero_tail(df, add_tail_min, dt_minutes):
        out = df.copy()
        n_extra = int(round(add_tail_min / dt_minutes)) + 1
        last_time = int(out["time_sec"].iloc[-1])
        for i in range(1, n_extra + 1):
            out.loc[len(out)] = [last_time + i * dt_minutes * 60, 0.0]
        return out

    def write_rainfall_txt(df, txt_path, dt_minutes):
        dt_seconds = dt_minutes * 60
        with open(txt_path, "w", encoding="utf-8") as f:
            f.write("* * *\n")
            f.write("* * * rainfall ***\n")
            f.write("* * *\n")
            f.write(f"{len(df)}\n")
            f.write("* * *\n")
            for _, row in df.iterrows():
                rainfall_mps = (row["depth_in"] * 0.0254) / dt_seconds
                f.write(f"{int(row['time_sec'])}\t{rainfall_mps:.10f}\n")

    lines = atlas14_csv.read_text(errors="ignore").splitlines()
    hdr_idx = next(i for i, line in enumerate(lines) if line.lower().startswith("by duration"))
    header = [x.strip() for x in lines[hdr_idx].split(",")]
    return_periods = [x for x in header[1:] if x]

    rows = []
    for line in lines[hdr_idx + 1:]:
        parts = [x.strip() for x in line.split(",")]
        first = parts[0].lower()
        if (not line.strip()) or first.startswith("date/time") or first.startswith("pyruntime"):
            break
        rows.append([parts[0].replace(":", "").strip()] + [x for x in parts[1:] if x != ""])

    noaa = pd.DataFrame(rows, columns=["Duration"] + return_periods)
    noaa["minutes"] = noaa["Duration"].apply(duration_to_minutes)

    idf_params = {}
    for rp in return_periods:
        fit = noaa.loc[noaa["minutes"] <= max_fit_minutes, ["minutes", rp]].copy()
        fit[rp] = pd.to_numeric(fit[rp], errors="coerce")
        fit = fit.dropna()

        t_min = fit["minutes"].to_numpy(float)
        depth_in = fit[rp].to_numpy(float)
        intensity = depth_in / (t_min / 60.0)

        params, _ = curve_fit(
            idf_func,
            t_min,
            intensity,
            p0=[1000.0, 10.0, 0.7],
            bounds=([0.0, 0.0, 0.0], [np.inf, np.inf, 5.0]),
            maxfev=200000,
        )
        idf_params[rp] = dict(zip(["a", "b", "c"], params))

    summary = []
    for sc in scenarios:
        p = idf_params[sc["return_period"]]
        hy = chicago_hyetograph(
            duration_hours=sc["storm_duration_hours"],
            dt_minutes=dt_minutes,
            a=p["a"],
            b=p["b"],
            c=p["c"],
            r=r_peak,
        )
        hy_out = append_zero_tail(hy, sc["add_tail_min"], dt_minutes)
        txt_name = f"Rainfall_Data_{sc['file_no']}.txt"
        txt_path = output_dir / txt_name
        write_rainfall_txt(hy_out, txt_path, dt_minutes)

        summary.append(
            {
                "file_no": sc["file_no"],
                "file_name": txt_name,
                "return_period": sc["return_period"],
                "storm_duration_hr": sc["storm_duration_hours"],
                "extra_zero_tail_min": sc["add_tail_min"],
                "n_points": len(hy_out),
                "output_path": str(txt_path),
            }
        )

    summary_df = pd.DataFrame(summary).sort_values("file_no")
    summary_csv = output_dir / "Rainfall_Scenario_Summary.csv"
    summary_df.to_csv(summary_csv, index=False)
    return summary_df


def main(argv=None):
    parser = argparse.ArgumentParser(
        description=(
            "Generate Chicago design storm rainfall files from NOAA Atlas 14"
        )
    )
    parser.add_argument(
        "output_dir",
        nargs="?",
        default=None,
        help=(
            "Directory to write the Atlas 14 CSV, rainfall .txt files, and summary CSV. "
            "Defaults to a directory named <lat>_<lon> in the current directory."
        ),
    )
    parser.add_argument(
        "lat", type=float, help="Latitude in decimal degrees (-90 to 90)"
    )
    parser.add_argument(
        "lon", type=float, help="Longitude in decimal degrees (-180 to 180)"
    )
    args = parser.parse_args(argv)
    output_dir = args.output_dir
    if output_dir is None:
        output_dir = f"{args.lat}_{args.lon}"

    downloaded_file = part1_download_atlas14(args.lat, args.lon, output_dir)
    summary_df = part2_generate_rainfall_files(downloaded_file, output_dir)

    print(downloaded_file)
    print(summary_df)


if __name__ == "__main__":
    main()
